const Images = {
  // images
  imgLogo: require('../assets/images/logo.png'), // 앱 로고
  imgOtherLogo: require('../assets/images/other-logo.png'), // 앱 로고 2
  imgCafeProfile: require('../assets/images/img-cafe-banner-edit.png'), // pub
  imgEditPhoto: require('../assets/images/btn-edit-photo.png'),
  imgRadioBtnOn: require('../assets/images/business-btn-radio-slelect.png'),
  imgRadioBtnOff: require('../assets/images/business-radio-unselect.png'),
  imgMenuEdit01: require('../assets/images/img-menu-edit-01.png'),
  imgRecommendCafe: require('../assets/images/imgRecommendCafe.png'),
  imgCompleteJoin: require('../assets/images/check-complete-big.png'),
  imgMainCafeCardImg: require('../assets/images/img-cafe-02.png'),
  imgPubCafeProfileInfo: require('../assets/images/invalid-name.png'),
  imgPubSigMenu: require('../assets/images/img-menu-01.png'),
  imgCouponBack: require('../assets/images/combined-shape.png'),
  imgPubBarcode: require('../assets/images/img-barcode.png'),
  imgPubQR: require('../assets/images/img-barcode-qr.png'),
  imgStampBack: require('../assets/images/img-stamp-back.png'),
  imgStampLine: require('../assets/images/line-3.png'),
  imgPubFullVideo: require('../assets/images/img-video-play.png'),
  imgPubProfile: require('../assets/images/stamp-profile.png'),
  // icons
  icoMore: require('../assets/images/ico-more.png'),
  icoCloseX: require('../assets/images/ic-basic-x.png'),
  icoCheckOff: require('../assets/images/check-check-click-dim.png'),
  icoCheckOn: require('../assets/images/check-check-click-select.png'),
  icoNaver: require('../assets/images/ico-naver.png'),
  icoKakao: require('../assets/images/ico-kakao.png'),
  icoBottomHome: require('../assets/images/nav-home-dim.png'), // 바텀 탭 홈 아이콘
  icoBottomHomeOn: require('../assets/images/nav-home-select.png'), // 바텀 탭 홈 아이콘 active
  icoBottomFavorite: require('../assets/images/nav-heart-dim.png'),
  icoBottomFavoriteOn: require('../assets/images/nav-heart-select.png'),
  icoBottomTodayMenu: require('../assets/images/nav-video-dim.png'),
  icoBottomTodayMenuOn: require('../assets/images/nav-video-select.png'),
  icoBottomMyPage: require('../assets/images/nav-user-dim.png'),
  icoBottomMyPageOn: require('../assets/images/nav-user-select.png'),
  icoCompass: require('../assets/images/ic-basic-map.png'),
  icoArrowBottom: require('../assets/images/ic-basic-down.png'),
  icoSearch: require('../assets/images/ic-basic-small-search.png'),
  icoDirection: require('../assets/images/btn-direction.png'),
  icoDirectionSmall: require('../assets/images/ic-basic-small-direction.png'),
  icoHeart: require('../assets/images/ic-heart-small-select.png'),
  icoBarcode: require('../assets/images/ohter-barcode.png'),
  icoHot: require('../assets/images/tag-hot.png'),
  icoBeen: require('../assets/images/other-beans.png'),
  icoReload: require('../assets/images/ic-basic-re.png'),
  icoQR: require('../assets/images/ic-basic-qr.png'),
  icoStampUse: require('../assets/images/ico-stamp-use.png'),
  icoStampEmpty: require('../assets/images/ico-stamp-empty.png'),
  icoStampFull: require('../assets/images/ico-stamp-full.png'),
  icoHeartEmpty: require('../assets/images/ic-heart-big-dim.png'),
  icoArrowRight: require('../assets/images/ic-basic-next.png'),
  icoArrowLeft: require('../assets/images/ic-basic-back.png'),
  icoService: require('../assets/images/ic-gray-serviec-center.png'),
  icoNoti: require('../assets/images/ic-gray-noti.png'),
  icoBtnPlay: require('../assets/images/btn-play.png'),
  icoBtnFloat: require('../assets/images/float-button.png'),
};

export default Images;
